baseURL = "https://kikuchi-et-al.github.io/"
title = "Kikuchi Labo"
googleAnalytics = "UA-123-456-789"
theme = "github-style"

[params]
author = "Nobuaki Kikuchi"
description = "My blog"
github = "kikuchi-et-al"
twitter = "kikuchi-et-al"
facebook = "nobuaki.kikuchi.14"
email = "kikuchi-et-al@domain.com"
utterances = "kikuchi-et-al/kikuchi-et-al.github.io"
avatar = "https://example.com/images/avatar.png"
url = "https://kikuchi-et-al.com"
