baseURL = "https://kikuchi-et-al.github.io/"
title = "Kikuchi Labo"
googleAnalytics = "UA-123-456-789"
theme = "github-style"

[params]
  author = "Nobuaki Kikuchi"
  description = "My blog"
  github = "kikuchi-et-al"
  twitter = "Kikuchi_et_al"
  email = ""
  utterances = "kikuchi-et-al/kikuchi-et-al.github.io"
  avatar = "https://example.com/images/avatar.png"
  url = ""
